config/routes.rb
ChatLogger::Application.routes.draw do
  root :to => 'users#index'

  get 'sessions/create'
  match '/auth/:provider/callback', :to => 'sessions#create'

  resources :spaces, :only => [] do
    resources :users, :only => :index do
      resources :chats, :only => [:index, :show]
    end
  end

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  attr_accessible :contact, :chat_messages

  # Users
  belongs_to :user
  validates_presence_of :user
  belongs_to :contact, :class_name => 'User', :foreign_key => 'contact_id'
  validates_presence_of :contact

  # Chat messages
  has_many :chat_messages, :dependent => :destroy

  # Atualiza as chat messages do chat
  def refresh!(token)
    url = "/api/chats/#{self.cid}/chat_messages"
    messages = JSON.parse Connection.get(url, token).body
    return unless messages.count > self.chat_messages.count
    messages.each do | redu_message |
      unless ChatMessage.find_by_cmid(redu_message["id"])
        self.chat_messages << ChatMessage.create_by_api(redu_message, token)
      end
    end
  end

  # Atualiza todos os chats para todos os usuários de uma determinada disciplina
  # sob a condição de o usuário possuir token de acesso
  def self.refresh(current_space)
    current_space.users.each do | user |
      unless !user.token
        Chat.update_chats_for(user, current_space)
      end
    end
  end

  private

  # Atualiza todos os chats para um determinado usuário em relação a uma 
  # determinada disciplina
  def self.update_chats_for(user, space)
    token = user.token
    url = "/api/users/#{user.username}/chats"
    chats = JSON.parse Connection.get(url, token).body

    chats.each do | redu_chat |
      contact_link = redu_chat["links"].select { |l| l["rel"] == "contact" }
      contact = User.find_by_url(contact_link.first["href"])
      cid = redu_chat["id"]
      # Não criar chats para contatos não existentes ou não vinculados à disciplina
      if (contact && space.users.include?(contact) && !Chat.find_by_cid(cid))
        chat = create! do | chat |
          chat.cid = redu_chat["id"]
          chat.user = user
          chat.contact = contact
        end
        ChatMessage.create_messages_for(chat)
        user.chats << chat
      end
    end

    # Atualiza chats já existentes (que podem ter ganhado novas mensagens)
    user.chats.each do | chat |
      chat.refresh!(user.token)
    end
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_filter :check_login, :check_membership, :update_chats

  # GET /spaces/:space_id/users/:user_id/chats
  def index
    @space = current_space
    @user = User.find(params[:user_id])
    @chats = @user.chats
    render 'user_chats'
  end

  # GET /spaces/:space_id/users/:user_id/chats/
  def show
    @space = current_space
    @chat = Chat.find(params[:id])
  end
end

app/helpers/chats_helper.rb
module ChatsHelper  
  def messages_per_day(chat)
    per_day = Array.new
    all = Array.new
    day = 0
    chat.chat_messages.each do |message|
      if day != message.sent_at.day
        day = message.sent_at.day
        all << per_day if per_day.length != 0
        per_day = Array.new
      end
      per_day << message
    end
    all << (per_day.sort_by &:sent_at) if per_day.length != 0
    
    all
  end

  def sort_by_date

  end
end

app/views/chats/show.html.erb
<ul class="breadcrumb-mini">
  <li class="breadcrumb-mini-item breadcrumb-mini-compact icon-arrow-right-separator-gray_16_18-after">
    <%= link_to "Home", '/', 
                :class => "breadcrumb-mini-link icon-home-lightblue_16_18-before" %>
  </li>
  <li class="breadcrumb-mini-item icon-arrow-right-separator-gray_16_18-after">
    <%= link_to space_user_chats_path(@space.sid, @chat.user), :class => "breadcrumb-mini-link" do %>
      Conversas de <%= @chat.user.first_name %>
    <% end %>
  </li>
  <li class="breadcrumb-mini-item icon-arrow-right-separator-gray_16_18-after">
    Com <%= @chat.contact.role.name %> <%= @chat.contact.first_name %>
  </li>
</ul>
<% messages_per_day(@chat).each do | msg_per_day | %>
  <h6 class="pull-right"><%= msg_per_day.first.sent_at.to_s(:date) %></h6>
  <table class="table-with-borderradius">
    <tbody>
      <% msg_per_day.each do | msg | %>
        <tr>
          <td class="hcol"><%= msg.sent_at.to_s(:time) %></td>
          <td><%= msg.user.first_name %>: <%= msg.message %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br /><br />
<% end %>

app/views/chats/user_chats.html.erb
<ul class="breadcrumb-mini">
  <li class="breadcrumb-mini-item breadcrumb-mini-compact icon-arrow-right-separator-gray_16_18-after">
    <%= link_to root_path, '/', :class => "breadcrumb-mini-link icon-home-lightblue_16_18-before" %>
  </li>
  <li class="breadcrumb-mini-item icon-arrow-right-separator-gray_16_18-after">
    Conversas de <%= @user.first_name %>
  </li>
</ul>
<br /><br />
<div class="row">
  <div class="span7 offset1">
    <ul class="list-button">
      <% @chats.each do | chat | %>
        <li class="list-button-item">
          <%= link_to space_user_chat_path(@space.sid, @user, chat) do %>
            Conversa com <%= chat.contact.role.name %> <%= chat.contact.first_name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>